root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ."
  bin = "tmp\\main.exe"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "postgres-data", "redis-data"s]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = true
  follow_symlink = true
  full_bin = ""
  include_dir = []
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
